import './globals.css';
import { Martel_Sans } from 'next/font/google';
import { draftMode } from 'next/headers';

export const metadata = {
  title: 'Xiaotian Liu',
  description: 'Generated by create next app',
};

const martel_Sans = Martel_Sans({
  subsets: ['latin'],
  weight: ['400', '600'],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={martel_Sans.className}>
        {draftMode().isEnabled && (
          <p className="bg-orange-200 py-4 px-[6vw]">
            Draft mode is on! <ExitDraftModeLink className="underline" />
          </p>
        )}
        {children}
      </body>
    </html>
  );
}
